/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.tiket.bioskop;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Alfian
 */
public class Form_tiket extends javax.swing.JFrame {
    String jenis_tiket;
    /**
     * Creates new form Form_tiket
     */
    public Form_tiket() {
        initComponents();
        setLocationRelativeTo(this);
    }

    public void bersih(){
        Nama.setText(null);
        jComboBox1.setSelectedIndex(0);
        reguler.setSelected(false);
        ultra_xd.setSelected(false);
        atmos.setSelected(false);
        vip.setSelected(false);
        jamTayang.setSelectedIndex(0);
        BeliSpinner.setValue(1);
        Total_beli.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FilmGroup = new javax.swing.ButtonGroup();
        JenisTiketGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_proses = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        hargaSatuan = new javax.swing.JTextField();
        reguler = new javax.swing.JRadioButton();
        atmos = new javax.swing.JRadioButton();
        ultra_xd = new javax.swing.JRadioButton();
        vip = new javax.swing.JRadioButton();
        jamTayang = new javax.swing.JComboBox<>();
        Total_beli = new javax.swing.JTextField();
        JumlahBeli = new javax.swing.JTextField();
        BeliSpinner = new javax.swing.JSpinner();
        jComboBox1 = new javax.swing.JComboBox<>();
        btn_proses1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Pemesanan Tiket Bioskop XXI ");

        jLabel2.setText("Nama");

        jLabel3.setText("Film");

        jLabel4.setText("Jenis Tiket");

        jLabel5.setText("Jam Tayang");

        jLabel6.setText("Harga Tiket");

        jLabel7.setText("Jumlah Beli");

        btn_proses.setText("Proses");
        btn_proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prosesActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        jLabel8.setText("Total");

        JenisTiketGroup.add(reguler);
        reguler.setText("Reguler");
        reguler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regulerActionPerformed(evt);
            }
        });

        JenisTiketGroup.add(atmos);
        atmos.setText("Ultra XD Atmos");
        atmos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atmosActionPerformed(evt);
            }
        });

        JenisTiketGroup.add(ultra_xd);
        ultra_xd.setText("Ultra XD");
        ultra_xd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultra_xdActionPerformed(evt);
            }
        });

        JenisTiketGroup.add(vip);
        vip.setText("VIP");
        vip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vipActionPerformed(evt);
            }
        });

        jamTayang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10.00", "14.00", "17.00", "20.00", "22.00" }));

        Total_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_beliActionPerformed(evt);
            }
        });

        JumlahBeli.setEditable(false);

        BeliSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        BeliSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                catchValueSpinner(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Avengers", "Spider-Man", "Fast Furious", "Guardian Galaxy", "Deadpool" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        btn_proses1.setText("Pesan");
        btn_proses1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proses1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Nama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btn_proses)
                        .addGap(38, 38, 38)
                        .addComponent(btn_hapus))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(89, 89, 89)
                            .addComponent(Total_beli, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_proses1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4))
                            .addGap(55, 55, 55)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(reguler)
                                    .addGap(18, 18, 18)
                                    .addComponent(atmos)
                                    .addGap(18, 18, 18)
                                    .addComponent(ultra_xd)
                                    .addGap(18, 18, 18)
                                    .addComponent(vip))
                                .addComponent(jamTayang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(hargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(JumlahBeli)
                                        .addGap(18, 18, 18)
                                        .addComponent(BeliSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(reguler)
                    .addComponent(atmos)
                    .addComponent(ultra_xd)
                    .addComponent(vip))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jamTayang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(hargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BeliSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_proses)
                    .addComponent(btn_hapus))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Total_beli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_proses1))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regulerActionPerformed
        jenis_tiket = reguler.getText();
        hargaSatuan.setText("20000");
    }//GEN-LAST:event_regulerActionPerformed

    private void atmosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atmosActionPerformed
        // TODO add your handling code here:
        jenis_tiket = atmos.getText();
        hargaSatuan.setText("50000");
    }//GEN-LAST:event_atmosActionPerformed

    private void ultra_xdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultra_xdActionPerformed
        // TODO add your handling code here:
        jenis_tiket = ultra_xd.getText();
        hargaSatuan.setText("80000");
    }//GEN-LAST:event_ultra_xdActionPerformed

    private void vipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vipActionPerformed
        // TODO add your handling code here:
        jenis_tiket = vip.getText();
        hargaSatuan.setText("100000");
    }//GEN-LAST:event_vipActionPerformed

    private void btn_prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prosesActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt (hargaSatuan.getText());
        int b = Integer.parseInt(JumlahBeli.getText());
        int hasil = a * b;
        Total_beli.setText("Rp " + hasil);
        
        
        
    }//GEN-LAST:event_btn_prosesActionPerformed

    private void catchValueSpinner(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_catchValueSpinner
        // TODO add your handling code here:
      
        String spinner = "changed";
        Integer myInt = (Integer)BeliSpinner.getValue();
        spinner = myInt.toString();
        JumlahBeli.setText(spinner);
        
    }//GEN-LAST:event_catchValueSpinner

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        Nama.setText("");
        hargaSatuan.setText("");
        Total_beli.setText("");
        JumlahBeli.setText("");
        BeliSpinner.setValue(1);
        
        
       FilmGroup.clearSelection();
       JenisTiketGroup.clearSelection();
        
        
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void Total_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_beliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total_beliActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btn_proses1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proses1ActionPerformed
        // TODO add your handling code here:
        try {
                Connection c = (Connection) ClassDB.getKoneksi();
                Statement st = (Statement) c.createStatement();
                
                String sql = "INSERT INTO pembelian VALUES ('"+Nama.getText()+"','"+jComboBox1.getSelectedItem()+"','"+jenis_tiket+"','"+jamTayang.getSelectedItem()+"','"+hargaSatuan.getText()+"', '"+BeliSpinner.getValue()+"', '"+Total_beli.getText()+"')";
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
                bersih();
                
                
            } catch (SQLException ex) {
               JOptionPane.showMessageDialog(this, ex);
            }
    }//GEN-LAST:event_btn_proses1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_tiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner BeliSpinner;
    private javax.swing.ButtonGroup FilmGroup;
    private javax.swing.ButtonGroup JenisTiketGroup;
    private javax.swing.JTextField JumlahBeli;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Total_beli;
    private javax.swing.JRadioButton atmos;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_proses;
    private javax.swing.JButton btn_proses1;
    private javax.swing.JTextField hargaSatuan;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> jamTayang;
    private javax.swing.JRadioButton reguler;
    private javax.swing.JRadioButton ultra_xd;
    private javax.swing.JRadioButton vip;
    // End of variables declaration//GEN-END:variables
}
