/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.tiket.bioskop;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author ASUS
 */
public class Pembelian extends javax.swing.JFrame {
    String jenis_tiket;
    private DefaultTableModel model;
    /**
     * Creates new form Pembelian
     */
    public Pembelian() {
        initComponents();
        setLocationRelativeTo(this);
        LoadData();
    }
    public void bersih(){
        Nama.setText(null);
        jComboBox1.setSelectedIndex(0);
        reguler.setSelected(false);
        ultra_xd.setSelected(false);
        atmos.setSelected(false);
        vip.setSelected(false);
        jamTayang.setSelectedIndex(0);
//        BeliSpinner.setValue(1);
        Total_beli.setText(null);
    }
    
    public void LoadData() {
        model = new DefaultTableModel();
        jTable1.setModel(model);
        model.addColumn("NAMA");
        model.addColumn("FILM");
        model.addColumn("JENIS TIKET");
        model.addColumn("JAM TAYANG");
        model.addColumn("HARGA");
        model.addColumn("JUMLAH");
        model.addColumn("TOTAL");
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        try {
            Connection c = (Connection) ClassDB.getKoneksi();
            Statement s = (Statement) c.createStatement();
            String sql = "SELECT * FROM pembelian";
            ResultSetImpl r = (ResultSetImpl) s.executeQuery(sql);
            
            while (r.next()) {                
                Object[] o = new Object[15];
                o[0] = r.getString("nama");
                o[1] = r.getString("film");
                o[2] = r.getString("jenis_tiket");
                o[3] = r.getString("jam_tayang");
                o[4] = r.getString("harga");
                o[5] = r.getString("jml");
                o[6] = r.getString("total");
                model.addRow(o);              
            }
            for (int i = 0; i < model.getColumnCount(); i++) {
                TableColumn column = jTable1.getColumnModel().getColumn(i);
                if (i == 0) column.setPreferredWidth(150);
                if (i == 1) column.setPreferredWidth(150);
                if (i == 2) column.setPreferredWidth(180);
                if (i == 3) column.setPreferredWidth(180);
                if (i == 4) column.setPreferredWidth(100);
                if (i == 5) column.setPreferredWidth(100);
                if (i == 6) column.setPreferredWidth(180);
                
            }
            r.close();
            s.close();
  
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        hargaSatuan = new javax.swing.JTextField();
        reguler = new javax.swing.JRadioButton();
        atmos = new javax.swing.JRadioButton();
        ultra_xd = new javax.swing.JRadioButton();
        vip = new javax.swing.JRadioButton();
        jamTayang = new javax.swing.JComboBox<>();
        Total_beli = new javax.swing.JTextField();
        JumlahBeli = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        btn_simpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_edit = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        btn_proses = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Pemesanan Tiket Bioskop XXI ");

        jLabel2.setText("Nama");

        jLabel3.setText("Film");

        jLabel4.setText("Jenis Tiket");

        jLabel5.setText("Jam Tayang");

        jLabel6.setText("Harga Tiket");

        jLabel7.setText("Jumlah Beli");

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        jLabel8.setText("Total");

        reguler.setText("Reguler");
        reguler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regulerActionPerformed(evt);
            }
        });

        atmos.setText("Ultra XD Atmos");
        atmos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atmosActionPerformed(evt);
            }
        });

        ultra_xd.setText("Ultra XD");
        ultra_xd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultra_xdActionPerformed(evt);
            }
        });

        vip.setText("VIP");
        vip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vipActionPerformed(evt);
            }
        });

        jamTayang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10.00", "14.00", "17.00", "20.00", "22.00" }));

        Total_beli.setEditable(false);
        Total_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_beliActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Avengers", "Spider-Man", "Fast Furious", "Guardian Galaxy", "Deadpool" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        btn_proses.setText("Proses");
        btn_proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prosesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Nama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(reguler)
                                        .addGap(18, 18, 18)
                                        .addComponent(atmos)
                                        .addGap(18, 18, 18)
                                        .addComponent(ultra_xd)
                                        .addGap(18, 18, 18)
                                        .addComponent(vip))
                                    .addComponent(jamTayang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(hargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(JumlahBeli)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Total_beli, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(btn_proses))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btn_simpan)
                        .addGap(18, 18, 18)
                        .addComponent(btn_hapus)
                        .addGap(18, 18, 18)
                        .addComponent(btn_edit)
                        .addGap(18, 18, 18)
                        .addComponent(btn_batal)))
                .addContainerGap(10, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(reguler)
                    .addComponent(atmos)
                    .addComponent(ultra_xd)
                    .addComponent(vip))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jamTayang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(hargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Total_beli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_proses))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_hapus)
                    .addComponent(btn_simpan)
                    .addComponent(btn_edit)
                    .addComponent(btn_batal))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        try {
                    Connection c = (Connection) ClassDB.getKoneksi();
                    Statement st = (Statement) c.createStatement();

                    String sql = "DELETE FROM pembelian WHERE nama = '"+Nama.getText()+"'";
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                    LoadData();
                    bersih();

                } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(this, ex);
                }

    }//GEN-LAST:event_btn_hapusActionPerformed

    private void regulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regulerActionPerformed
        jenis_tiket = reguler.getText();
        atmos.setSelected(false);
        ultra_xd.setSelected(false);
        vip.setSelected(false);
        hargaSatuan.setText("20000");
        
    }//GEN-LAST:event_regulerActionPerformed

    private void atmosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atmosActionPerformed
        // TODO add your handling code here:
        jenis_tiket = atmos.getText();
        reguler.setSelected(false);
        ultra_xd.setSelected(false);
        vip.setSelected(false);
        hargaSatuan.setText("50000");
        
    }//GEN-LAST:event_atmosActionPerformed

    private void ultra_xdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultra_xdActionPerformed
        // TODO add your handling code here:
        jenis_tiket = ultra_xd.getText();
        atmos.setSelected(false);
        reguler.setSelected(false);
        vip.setSelected(false);
        hargaSatuan.setText("80000");
        
    }//GEN-LAST:event_ultra_xdActionPerformed

    private void vipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vipActionPerformed
        // TODO add your handling code here:
        jenis_tiket = vip.getText();
        atmos.setSelected(false);
        ultra_xd.setSelected(false);
        reguler.setSelected(false);
        hargaSatuan.setText("100000");
        
    }//GEN-LAST:event_vipActionPerformed

    private void Total_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_beliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total_beliActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        try {
            Connection c = (Connection) ClassDB.getKoneksi();
            Statement st = (Statement) c.createStatement();

            String sql = "INSERT INTO pembelian VALUES ('"+Nama.getText()+"','"+jComboBox1.getSelectedItem()+"','"+jenis_tiket+"','"+jamTayang.getSelectedItem()+"','"+hargaSatuan.getText()+"', '"+JumlahBeli.getText()+"', '"+Total_beli.getText()+"')";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
            bersih();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        Nama.disable();
        int i = jTable1.getSelectedRow();
        
        if (i == -1) {
            return;
        } else {
            String nama = (String) model.getValueAt(i, 0);
            Nama.setText(nama);
            String film = (String) model.getValueAt(i, 1);
            jComboBox1.setSelectedItem(film);
            if (jTable1.getValueAt(i, 2).equals("Reguler")) {
                reguler.setSelected(true);
                atmos.setSelected(false);
                ultra_xd.setSelected(false);
                vip.setSelected(false);
            } else if (jTable1.getValueAt(i, 2).equals("Ultra XD Atmos")) {
                reguler.setSelected(false);
                atmos.setSelected(true);
                ultra_xd.setSelected(false);
                vip.setSelected(false);
            } else if (jTable1.getValueAt(i, 2).equals("Ultra XD")) {
                reguler.setSelected(false);
                atmos.setSelected(false);
                ultra_xd.setSelected(true);
                vip.setSelected(false);
            } else if (jTable1.getValueAt(i, 2).equals("VIP")) {
                reguler.setSelected(false);
                atmos.setSelected(false);
                ultra_xd.setSelected(false);
                vip.setSelected(true);
            }
            String jam = (String) model.getValueAt(i, 3);
            jamTayang.setSelectedItem(jam);
            String harga = (String) model.getValueAt(i, 4);
            hargaSatuan.setText(harga);
            String jml = (String) model.getValueAt(i, 5);
            JumlahBeli.setText(jml);
            String total = (String) model.getValueAt(i, 6);
            Total_beli.setText(total);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        try {
                Connection c = (Connection) ClassDB.getKoneksi();
                Statement st = (Statement) c.createStatement();
                
                String sql = "UPDATE pembelian SET nama = '"+Nama.getText()+"', film = '"+jComboBox1.getSelectedItem()+"', jenis_tiket = '"+jenis_tiket+"', jam_tayang = '"+jamTayang.getSelectedItem()+"', jml = '"+JumlahBeli.getText()+"', total = '"+Total_beli.getText()+"' WHERE nama = '"+Nama.getText()+"'";
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(this, "Data Berhasil Diubah");
                LoadData();
                bersih();
                
            } catch (SQLException ex) {
               JOptionPane.showMessageDialog(this, ex);
            }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        String spinner = "changed";
        Integer myInt = (Integer)jSpinner1.getValue();
        spinner = myInt.toString();
        JumlahBeli.setText(spinner);
    }//GEN-LAST:event_jSpinner1StateChanged

    private void btn_prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prosesActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt (hargaSatuan.getText());
        int b = Integer.parseInt(JumlahBeli.getText());
        int hasil = a * b;
        Total_beli.setText("Rp " + hasil);
    }//GEN-LAST:event_btn_prosesActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Pembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JumlahBeli;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Total_beli;
    private javax.swing.JRadioButton atmos;
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_proses;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JTextField hargaSatuan;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jamTayang;
    private javax.swing.JRadioButton reguler;
    private javax.swing.JRadioButton ultra_xd;
    private javax.swing.JRadioButton vip;
    // End of variables declaration//GEN-END:variables
}
